### ISSUE TITLE
Add Loaders ( Multiple Places )

### ISSUE THREAD

**Issue by masterpranay1** [masterpranay1/link-sharing-app#2]
A Loader is required at following place : 

- [x] #3
![image](https://github.com/masterpranay1/link-sharing-app/assets/58875281/020a5094-0acf-4ee9-9826-1b90c26a5d6b)

- [x] Image Loading
It seems like There is no image at first ( A loading animation or text will help increase UX )
![image](https://github.com/masterpranay1/link-sharing-app/assets/58875281/5e42efba-08c5-4d25-8bf1-a1c8bdb70152)

- [x] Save and Submit Button
Prevent Multiple clicks with the loading animation

- [x] Add shadow loaders in the Mockup Preview and actual preview

- [x] Log out loading
Navigate only after the logout process is complete

**Comment by uniquesonu** [comment]
.

**Comment by masterpranay1** [comment]
Any Update??

**Comment by masterpranay1** [comment]
Feature added in PR #9
